apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: springboot
  name: spring-controller
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: springboot
    spec:
      containers:
        - image: pzombade/spring-boot-mongo2
          name: springboot
          ports:
            - name: springboot
              containerPort: 8080
  selector:
    matchLabels:
      name: springboot
---
# Node Port Service
